language: ruby
env:
  - CI=true
before_script:
  - "bundle exec rake db:prepare"
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
notifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
